### ISSUE TITLE
MAKKAH method overwrites tuning of ALL timings during Ramadan.

### ISSUE THREAD

**Issue by meezaan** [islamic-network/api.aladhan.com#24]
http://api.aladhan.com/v1/calendar?latitude=24.490485&longitude=54.395048&month=6&year=2019&method=4&tune=0,4,-3,2,3,5,0,-10,0

produces 

`
offset: {
Imsak: 0,
Fajr: 0,
Sunrise: 0,
Dhuhr: 0,
Asr: 0,
Maghrib: 0,
Sunset: 0,
Isha: "30 min",
Midnight: 0,
`
It should still honour the others, whilst always overwriting Isha to 30 mins.

**Comment by DPANET** [comment]
Also if you can make the isha return value type number to ensure consistency without the need of min string.

**Comment by meezaan** [comment]
@DPANET I can't because it's explicitly mins.

**Comment by meezaan** [comment]
@DPANET This is now fixed. Adjustment takes effect, except for Isha, which is overwritten to 30 mins, always.
