### ISSUE TITLE
Send improvements upstream?

### ISSUE THREAD

**Issue by sshaikh** [islamic-network/api.aladhan.com#27]
Impressive website and work, but I was wondering if there was an available list of improvements that have been made to the original code at http://praytimes.org?

I want to use the Python code, but it hasn't been updated there in years. I'll be happy to port over and make available any improvements you've made if there's a clear list of them?

**Comment by meezaan** [comment]
I don't have a definitive list, but I could put one together in due course. The actual ported and amended library is here: https://github.com/meezaan/prayer-times

You might be better of just converting that to python - it still needs some improvement (especially in terms of arranging the code) - but it is functional as is and is used by the API for the calculation.

**Comment by sshaikh** [comment]
Thank you for the link to the repo - I can use the commit history from there for now.
