### ISSUE TITLE
Getting status code 429 often

### ISSUE THREAD

**Issue by usmanp24** [islamic-network/api.aladhan.com#31]
Hi,
First of all, Thanks for this great product.
Secondly, I am using api.aladhan.com to get the timings of namaz in my project and often i get status code 429.
So my question is what is Maximum requests per minute set in api.aladhan.com server?
And can it be increased?

**Comment by meezaan** [comment]
Salaam @usmanp24. Can you please confirm if you are coming over IPv4 or IPv6. Due to the limitations of container orchestration platforms today, the IPv6 request pool is shared.

If you're coming over IPv4, can you please share your IP address?

**Comment by usmanp24** [comment]
WalaikumSalam,
I am coming from ipv4. And the IP of the server is 15.185.125.160
Thanks,

**Comment by meezaan** [comment]
I see 2 of 80 requests with a 429 in the last 24 hours from that IP. Does that sound right?

That's nowhere near the threshold. I will investigate.

**Comment by usmanp24** [comment]
Yes, I have received two 429 response in last 24 hours so far.
Currently APP is in Development state and soon will be made LIVE for the end users. And these requests will increase drasatically. So will you please tell me what is the threshold value?
Thanks,

**Comment by meezaan** [comment]
The threshhold is 250 requests every 30 seconds. If you have a genuine use case I can give you an API key and increase the limit. But you clearly didn't make that number of requests so i need to have a look at why you got the 429.

Please give me a couple of days - I coded the firewall myself but it's been a while.

**Comment by usmanp24** [comment]
Thanks a lot
Please do let me know about the investigations.
And it will be great if you can provide the API key and increase the limit because I may need to use it.

**Comment by usmanp24** [comment]
Here is my email address: usmanp.24@gmail.com
Please share the API key if it is easy for you to do it.
Thanks

**Comment by usmanp24** [comment]
Assalam-o-Alaikum,
Did you get the chance to look at this issue. I have been getting 429 more and more lately.
Thanks,

**Comment by meezaan** [comment]
Alaykum Salaaam Usman. Sorry i have been away for a couple of days and will send you something today insha Allah.
