### ISSUE TITLE
Add Moonsighting Prayer Times Method

### ISSUE THREAD

**Issue by meezaan** [islamic-network/api.aladhan.com#36]
Add the Moonsighting.com calculation method for Fajr and Isha to the API.

**Comment by spamawaymate** [comment]
This might help with this: [https://github.com/PrayerTimeResearch/PrayerTimeAPI](url)

**Comment by meezaan** [comment]
Thank you @spamawaymate.

**Comment by meezaan** [comment]
A library has been created to do this @ https://github.com/islamic-network/prayer-times-moonsighting.

**Comment by meezaan** [comment]
Completed, but docs need to be added.

Examples:
http://api.aladhan.com/v1/timingsByCity/21-04-2020?city=London&country=UK&method=15&shafaq=abyad
http://api.aladhan.com/v1/timingsByCity/21-04-2020?city=London&country=UK&method=15&shafaq=ahmer
http://api.aladhan.com/v1/timingsByCity/21-04-2020?city=London&country=UK&method=15&shafaq=general

**Comment by meezaan** [comment]
Documentation updated:
https://github.com/islamic-network/api.aladhan.com/commit/1df2d20e8098f7f6c3d4c55d9a892045dfd99a01
https://github.com/islamic-network/aladhan.com/commit/1c44922248de4e77c7ee6b9734a948cff7676cff
