### ISSUE TITLE
limited API 

### ISSUE THREAD

**Issue by hiwa-jalal** [islamic-network/api.aladhan.com#38]
are API calls unlimited and free, if yes then why I am getting this message 
{"message":"API rate limit exceeded"}
if it's not free then where are the pricing options?

**Comment by meezaan** [comment]
It's a free service, so rate limiting is in place to stop any abuse.

The API currently allows 240 requests per minute per IP.

If you're working to use it for a free service, please get in touch via the support email address with your use case and we can issue with you with a key.

If you're working to create a paid service, you still need to get in touch and we can talk about your use case.

**Comment by hiwa-jalal** [comment]
i am going to use it in an app that I will publish on play store, do I need a key?

**Comment by meezaan** [comment]
If it's in the Play Store you like won't hit the rate limit because each user should have a separate IP. I think you'll be fine.

Just try to cache where ever you can and if you run into a problem again please reach out and we can look at a key if needed.
