### ISSUE TITLE
No such file or directory in /var/www/config/init.php

### ISSUE THREAD

**Issue by malikovss** [islamic-network/api.aladhan.com#41]
I couldn't use this project. 
It runned but not worked for me. 
I faced this issue when i send a request to localhost:7070 (aa-app)
`require_once(/var/www/config/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/config/init.php on line 8`

**Comment by meezaan** [comment]
Please run composer install locally. On first run when the volume mounts it overwrites the vendor folder in the container with an empty 1 on the host.
