### ISSUE TITLE
Not working for about 3 days now

### ISSUE THREAD

**Issue by devshot-dotcom** [islamic-network/api.aladhan.com#43]
I'm developing an android app that uses this API as the core requirement and now, the app has been developed but for 3 days I'm getting `Forbidden (500)` and sometimes even `Not Found (403)` errors but the main issue is that this happens through my app, and not through the browser. I'm so thankful for this API but now I see there was the same issue reported by someone about a week ago so, should I keep using the API or look for alternative solutions?

**Comment by meezaan** [comment]
Salaam brother. We are still investigating. I've swapped out every component of the K8S cluster, so now I can only imagine it is a problem with Linode.

I will be spinning up a new cluster on an older version this evening and will post back the progress.

**Comment by meezaan** [comment]
Salaam @devshot-dotcom.

I've just migrated to the new cluster and updated the A record.

You should no longer see the 500. The 403 was the API Gateway's bot detection which was removed earlier in the day.

**Comment by devshot-dotcom** [comment]
Wa-Alaikum-As-Salam brother, thank you for the response, I'll have a look in an hour or two and share the current state of the issue

**Comment by devshot-dotcom** [comment]
@meezaan Salaam brother, the issue has been successfully resolved, I guess I was requesting a lot cuz of development, should have used some template data, the behaviour might be similar to that of a bot `chuckle.` Now it's working pretty fine, hope this continues. Have a good day brother. Assalam U Alaikum
