### ISSUE TITLE
Inconsistent Hijri day between calendar and v1 timingsByCity

### ISSUE THREAD

**Issue by AlGantori** [islamic-network/api.aladhan.com#51]
http://api.aladhan.com/v1/timingsByCity?city=los%20angeles&region=CA&country=USA&method=2 

returns JSON with Hijri date as  Shaban 29th and we are Ramadhan 1st  (Saturday April 2nd 2022) that's 2 days off.

![image](https://user-images.githubusercontent.com/11699920/161385698-89c9171f-235c-4617-98c6-233ab94dff4b.png)

Whereas the following calendar is correct how do we go about fixing the timingsByCity endpoint to return correct Hijri date?

https://aladhan.com/ramadan-prayer-times/2022/Los Angeles/CA, USA

![image](https://user-images.githubusercontent.com/11699920/161385776-7ded353b-5d4d-4dbd-b198-bfdfa537b5dc.png)

Thank you.

**Comment by meezaan** [comment]
Please see https://community.islamic.network/d/1-the-aladhan-api-has-the-incorrect-hijri-date.
