### ISSUE TITLE
state or region parameter to timingsByCity is not recognized or validated correctly

### ISSUE THREAD

**Issue by AlGantori** [islamic-network/api.aladhan.com#52]
Is "region" a recognized parameter in the URL? it's not in the docs at.  
https://aladhan.com/prayer-times-api#GetTimingsByCity

![image](https://user-images.githubusercontent.com/11699920/161386530-4d770d7f-e124-4753-91ff-565c00fd482d.png)

The API does not complain about unknown parameters like foo=CA however documented parameter state=CA is not accepted either but state=California is accepted.

http://api.aladhan.com/v1/timingsByCity?city=los%20angeles&state=CA&country=USA&method=2
also NOT accepted the following

http://api.aladhan.com/v1/timingsByCity?city=Corvallis&state=Oregon&country=USA&method=2

http://api.aladhan.com/v1/timingsByCity?city=Corvallis&state=OR&country=USA&method=2

![image](https://user-images.githubusercontent.com/11699920/161386985-b3e16b58-fd5d-41d8-bd9b-cac8219ebeb2.png)

Thank you.

**Comment by meezaan** [comment]
@AlGantori for me http://api.aladhan.com/v1/timingsByCity?city=los%20angeles&state=CA&country=USA&method=2 returns a valid response. As does http://api.aladhan.com/v1/timingsByCity?city=Corvallis&state=OR&country=USA&method=2.

Can you please ping api.aladhan.com and let me know which IP address you see. I'll check if it at some point Google returned an error for geocoding and the errored value is cached in the cluster you are accessing.

**Comment by AlGantori** [comment]
Following either links will open new browser tabs every time I refresh, and always returns the same response code: 400, status "Bad Request"...

Here the result of the ping:
![image](https://user-images.githubusercontent.com/11699920/161445589-c46f0a5e-aecf-4658-aadc-0423dc254c54.png)

**Comment by meezaan** [comment]
Thank you. I will have a look today insha'Allah.

**Comment by meezaan** [comment]
I've flushed the cache, please try now.
