### ISSUE TITLE
Is the api down

### ISSUE THREAD

**Issue by kazimsadiq** [islamic-network/api.aladhan.com#59]
I cannot access the aladhan site/api

is it down?

**Comment by HishamAHai** [comment]
I can confirm it's down for me

**Comment by meezaan** [comment]
@kazimsadiq @HishamAHai No, it is not down - https://status.Islamic.network.

Where are you guys based? Can you flush your dns? Can you share the output of nslookup?

Are you unable to connect? What is the actual problem?

**Comment by HishamAHai** [comment]
here is the output of nslookup api.aladhan.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
api.aladhan.com	canonical name = geo.aladhan.com.
Name:	geo.aladhan.com
Address: 198.58.126.25
Name:	geo.aladhan.com
Address: 2600:3c00::f03c:92ff:fe0e:e6f9

For me the site is not loading and the api does not retrieve any data in my script.
Flushing the DNS did not resolve the problem on fedora linux 36

**Comment by meezaan** [comment]
You have the correct up address. Are you based in the US as you are hitting the Dallas cluster. Can you ping the domain at all? How about a curl -I. Does it return any headers?

**Comment by HishamAHai** [comment]
Sorry for the late answer, I'm based in Argentina and the output of curl -I is
`HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Sat, 20 Aug 2022 18:31:04 GMT
Content-Type: text/html
Content-Length: 138
Connection: keep-alive
Location: http://ip-198-58-126-25.cloudezapp.io/v1/timings/
adjustment=1
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-cache
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
X-Cloudez-Verify: 748de5c80d1b2bd6e52577dd0da0351509d64b37318294f11dbc36d6`

**Comment by meezaan** [comment]
@HishamAHai we discovered the issue as discussed on https://community.islamic.network/d/11-api-is-not-working/13 and it has just been fixed. It should be working fine now. Please do confirm. Thank you.

**Comment by HishamAHai** [comment]
Confirmed. Thanks for your amazing work
