### ISSUE TITLE
ISO 8061 format is wrong?

### ISSUE THREAD

**Issue by xAbdaziz** [islamic-network/api.aladhan.com#60]
I'm using the following endpoint 
`https://api.aladhan.com/v1/calendarByCity?city=Jeddah&country=SA&iso8601=true`

When I try to parse it in Golang get the following error
`panic: parsing time "\"2023-01-01T05:40:00+03:00 (+03)\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse " (+03)\"" as "\""`

After removing the `(+03)` part in the end, it works as intended

**Comment by xAbdaziz** [comment]
I also tried to parse it in https://time.lol with `(+03)` and It couldn't parse it either

**Comment by meezaan** [comment]
Which endpoint are you calling? I will have a look. I suspect the parenthesis may be an 'add-on' to the calendar endpoints.

**Comment by xAbdaziz** [comment]
> Which endpoint are you calling? I will have a look. I suspect the parenthesis may be an 'add-on' to the calendar endpoints.

I'm calling this: `https://api.aladhan.com/v1/calendarByCity?city=Jeddah&country=SA&iso8601=true`

**Comment by meezaan** [comment]
> > Which endpoint are you calling? I will have a look. I suspect the parenthesis may be an 'add-on' to the calendar endpoints.
> 
> I'm calling this: `https://api.aladhan.com/v1/calendarByCity?city=Jeddah&country=SA&iso8601=true`

I think I've found the cause. I'll try and commit a change in a couple days - I'll just need to test out a couple of things. But the code was added because without the iso format (which was a feature added later on) people used to think the timings were incorrect when daylight savings kicked in.

**Comment by xAbdaziz** [comment]
> > > Which endpoint are you calling? I will have a look. I suspect the parenthesis may be an 'add-on' to the calendar endpoints.
> > 
> > 
> > I'm calling this: `https://api.aladhan.com/v1/calendarByCity?city=Jeddah&country=SA&iso8601=true`
> 
> I think I've found the cause. I'll try and commit a change in a couple days - I'll just need to test out a couple of things. But the code was added because without the iso format (which was a feature added later on) people used to think the timings were incorrect when daylight savings kicked in.

Great 👍, btw the timings in `timingsByCity` are correct so I ended up using them instead

**Comment by meezaan** [comment]
Yes, because they look correct for one day, but when they appear together, they confuse people.
