### ISSUE TITLE
Tune setting not working when using a custom method

### ISSUE THREAD

**Issue by HichamBI** [islamic-network/api.aladhan.com#63]
Assalmou Alaykoum,

When using a custom calculation method with tune parameter, tune parameter is not taken into account and simply ignored.

For example : 

[https://api.aladhan.com/timingsByAddress?address=London, UK&method=99&methodSettings=18.5,null,17.5&tune=1,2,3,4,5](url)

![image](https://user-images.githubusercontent.com/8617460/220035212-ea9e8ae4-cc32-44de-8c54-73ea1f91c7a0.png)

If we chose a non custom calculation method, tune parameter is working well : 

[https://api.aladhan.com/timingsByAddress?address=London, UK&method=3&methodSettings=18.5,null,17.5&tune=1,2,3,4,5](url)

![image](https://user-images.githubusercontent.com/8617460/220082985-5e168694-e068-4899-a125-b8626effaaaa.png)

BR,
Hicham.

**Comment by meezaan** [comment]
> https://api.aladhan.com/timingsByAddress?address=London, UK&method=99&methodSettings=18.5,null,17.5&tune=1,2,3,4,5

Alaykum salaam. Thank you for identifying this. The tune parameters appear to have always been ignored for the custom method. I will push a fix shortly. Expect it to work in, God willing ~ 30 mins from this comment.

**Comment by HichamBI** [comment]
Thank you.
