### ISSUE TITLE
JSON returned by API endpoint v1 timingsByCity is not matching the demo app play link

### ISSUE THREAD

**Issue by AlGantori** [islamic-network/api.aladhan.com#64]
For March 11 2023 The "play" link Fajr time is displayed as **5:13 am** which matches expectation

https://aladhan.com/play/Corvallis/OR,%20USA
![image](https://user-images.githubusercontent.com/11699920/224508373-5525f963-fd2b-45c0-a272-b53ca8d2aa8c.png)

However, I am invoking the timingsByCity with the following code: 

```
let URL = `https://api.aladhan.com/v1/timingsByCity?country=${Country}&region=${Region}&city=${City}&method=${Method}&adjustment=${HijriCorrection}`
this.Load(URL)

```
actual request...

https://api.aladhan.com/v1/timingsByCity?country=US&region=Oregon&city=Corvallis&method=2&adjustment=1

and I get the following JSON with Fajr time as **5:00 am**

![image](https://user-images.githubusercontent.com/11699920/224508526-75eed9a0-3cbf-4a9b-a2b4-b31e8f8e186f.png)

what parameter(s) am I missing to match the timings displayed in the play link?
Also, I don't see a parameter regarding whether to use the system time or cloud time? if that matters?
Thank you.

**Comment by meezaan** [comment]
> For March 11 2023 The "play" link Fajr time is displayed as **5:13 am** which matches expectation
> 
> https://aladhan.com/play/Corvallis/OR,%20USA ![image](https://user-images.githubusercontent.com/11699920/224508373-5525f963-fd2b-45c0-a272-b53ca8d2aa8c.png)
> 
> However, I am invoking the timingsByCity with the following code:
> 
> ```
> let URL = `https://api.aladhan.com/v1/timingsByCity?country=${Country}&region=${Region}&city=${City}&method=${Method}&adjustment=${HijriCorrection}`
> this.Load(URL)
> ```
> 
> actual request...
> 
> https://api.aladhan.com/v1/timingsByCity?country=US&region=Oregon&city=Corvallis&method=2&adjustment=1
> 
> and I get the following JSON with Fajr time as **5:00 am**
> 
> ![image](https://user-images.githubusercontent.com/11699920/224508526-75eed9a0-3cbf-4a9b-a2b4-b31e8f8e186f.png)
> 
> what parameter(s) am I missing to match the timings displayed in the play link? Also, I don't see a parameter regarding whether to use the system time or cloud time? if that matters? Thank you.

You need to use the correct method - ISNA - to get the same result.

**Comment by AlGantori** [comment]
I am posting method=2 in my example above
https://api.aladhan.com/v1/timingsByCity?country=US&region=Oregon&city=Corvallis&method=2&adjustment=1
The returned JSON also says ISNA ?

![image](https://user-images.githubusercontent.com/11699920/224525011-577a18b0-2c53-4500-adc1-c85b360d8140.png)

**Comment by meezaan** [comment]
Where did you get the region query parameter from? The API only supports state, not region.

**Comment by AlGantori** [comment]
Back in issue https://github.com/islamic-network/api.aladhan.com/issues/52 I had asked whether "region" was an accepted parameters.   I must have gotten side-tracked with your fix to a different issue and never double checked the returned timings where correct.
Because I started using a geolocation service returning "region" I must have "believed" is was accepted by this API.
TODO: Perhaps your API can return an error about illegal parameters in the future.
The following is now returning the expected times 
https://api.aladhan.com/v1/timingsByCity/11-03-2023?country=US&state=Oregon&city=Corvallis&method=2&adjustment=1

Thank you for the catch, much appreciated.
Jazaakum Allahu Khayran!  and Ramadhan  Mubaarak and Kareem !!!

**Comment by meezaan** [comment]
> Back in issue #52 I had asked whether "region" was an accepted parameters. I must have gotten side-tracked with your fix to a different issue and never double checked the returned timings where correct. Because I started using a geolocation service returning "region" I must have "believed" is was accepted by this API. TODO: Perhaps your API can return an error about illegal parameters in the future. The following is now returning the expected times https://api.aladhan.com/v1/timingsByCity/11-03-2023?country=US&state=Oregon&city=Corvallis&method=2&adjustment=1
> 
> Thank you for the catch, much appreciated. Jazaakum Allahu Khayran! and Ramadhan Mubaarak and Kareem !!!

Illegal query parameters are simply ignored - throwing errors for those is bordering an extreme in my humble opinion. Sometimes client side JavaScript calls append a timestamp or random query parameter to bypass caching, and that would result in failing calls.

It's a public API, so flexibility is always important. But reading the documentation is always the simplest way to get it right. 

By the way, you can also just simply use the timingsByAddress endpoint, and just pass one string in the address query parameter.

JazakAllah for the Ramadan wishes! May yours be full of blessings too!
