### ISSUE TITLE
Addling a calculation method

### ISSUE THREAD

**Issue by TheRedM** [islamic-network/api.aladhan.com#67]
This is more of a request than an issue, please add Habous calculaion method (Morocco) trying to do a custom calculation or adding a time offset breaks the time accuracy of other days.

Here is the official Habous prayer times for reference.

https://www.habous.gov.ma/prieres/index.php

**Comment by meezaan** [comment]
> This is more of a request than an issue, please add Habous calculaion method (Morocco) trying to do a custom calculation or adding a time offset breaks the time accuracy of other days.
> 
> Here is the official Habous prayer times for reference.
> 
> https://www.habous.gov.ma/prieres/index.php

Adding a calculation method requires certain parameters - https://github.com/islamic-network/prayer-times/blob/master/src/PrayerTimes/Method.php#L110.

We would need an angle for Fajr and Isha. Would you happen to know what these are their calculation?
