### ISSUE TITLE
Calculation Custom Method Not Working

### ISSUE THREAD

**Issue by AbdennourNouaceur** [islamic-network/api.aladhan.com#68]
method=99&methodSettings=18.5%2Cnull%2C17.5 not working on these api calls
[Prayer Times Calendar](https://aladhan.com/prayer-times-api#GetCalendar) - http://api.aladhan.com/v1/calendar/:year/:month
[Prayer Times Calendar by address](https://aladhan.com/prayer-times-api#GetCalendarByAddress) - http://api.aladhan.com/v1/calendarByAddress/:year/:month
[Prayer Times Calendar by city](https://aladhan.com/prayer-times-api#GetCalendarByCitys) - http://api.aladhan.com/v1/calendarByCity/:year/:month
[Prayer Times Hijri Calendar](https://aladhan.com/prayer-times-api#GetHijriCalendar) - http://api.aladhan.com/v1/hijriCalendar/:year/:month
[Prayer Times Hijri Calendar by address](https://aladhan.com/prayer-times-api#GetHijriCalendarByAddress) - http://api.aladhan.com/v1/hijriCalendarByAddress/:year/:month
[Prayer Times Hijri Calendar by city](https://aladhan.com/prayer-times-api#GetHijriCalendarByCity) - http://api.aladhan.com/v1/hijriCalendarByCity/:year/:month

it only works on these api requests

[Timings](https://aladhan.com/prayer-times-api#GetTimings) - http://api.aladhan.com/v1/timings/:date
[Timings By Address](https://aladhan.com/prayer-times-api#GetTimingsByAddresss) - http://api.aladhan.com/v1/timingsByAddress/:date
[Timings By City](https://aladhan.com/prayer-times-api#GetTimingsByCity) - http://api.aladhan.com/v1/timingsByCity/:date

**Comment by meezaan** [comment]
Thank you for reporting.

I may have introduced it during the refactoring with Diyanet adjustments. Need more integration tests.

Insha Allah expect a resolution in 24 hours or so.

**Comment by AbdennourNouaceur** [comment]
the bug is fixed may god bless you
