### ISSUE TITLE
API does no longer returns yearly prayer times

### ISSUE THREAD

**Issue by nayefag** [islamic-network/api.aladhan.com#69]
The previous API used to take annual=true to return all 12 months in a year of prayer times.

The option seems to have been removed and the documentation says that if you omit the "month" option, it will be equivalent.

However, removing both "annual=true" and "month" seems to be equivalent to "month=1". 

I can't find a way to return prayer times for full year as it used to work before.

**Comment by meezaan** [comment]
@nayefag Can you please share the API call you are making? 

`https://api.aladhan.com/v1/calendarByCity/2017?city=London&country=United%20Kingdom&method=2` seems to return what I'd expect, all of 2017.

**Comment by nayefag** [comment]
I use this API 
/usr/bin/wget --quiet -O - 'http://api.aladhan.com/v1/calendar?latitude=51.5072&longitude=0.12760&method=2&timezonestring=America/Chicago&year=2024&midnightMode=1'

This used to work for me. I used to add "annual=true" and some dummy "month" value, but according to the latest docs this is no longer needed (just omitting month should work).

Thanks.

**Comment by meezaan** [comment]
> I use this API /usr/bin/wget --quiet -O - 'http://api.aladhan.com/v1/calendar?latitude=51.5072&longitude=0.12760&method=2&timezonestring=America/Chicago&year=2024&midnightMode=1'
> 
> This used to work for me. I used to add "annual=true" and some dummy "month" value, but according to the latest docs this is no longer needed (just omitting month should work).
> 
> Thanks.

I think you are not reading the docs right. You need to specify the year in the URL as the docs say: http://api.aladhan.com/v1/calendar/:year/:month. If you omit the month, you will get the year.

**Comment by meezaan** [comment]
Any luck @nayefag?

**Comment by nayefag** [comment]
/usr/bin/wget -O - 'http://api.aladhan.com/v1/calendar/:2024?latitude=51.5072&longitude=0.12760&method=2&timezonestring=America/Chicago&midnightMode=1'

...
HTTP request sent, awaiting response... 400 Bad Request
2024-01-04 09:57:14 ERROR 400: Bad Request.

This one I added a month:

 /usr/bin/wget -O - 'http://api.aladhan.com/v1/calendar/:2024:1?latitude=51.5072&longitude=0.12760&method=2&timezonestring=America/Chicago&midnightMode=1'



...
Connecting to api.aladhan.com (api.aladhan.com)|109.74.197.73|:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2024-01-04 09:59:36 ERROR 400: Bad Request.

**Comment by meezaan** [comment]
Why are you are a : before the year?

That just means it is a variable you need to specify. Variables in docs are usually specified as :varname or {varname}.

**Comment by nayefag** [comment]
My bad. I didn't know this.
Removing the : fixed the issue. Thanks for your help.
