### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource using Javascript.

### ISSUE THREAD

**Issue by iamjenechka** [islamic-network/api.aladhan.com#70]
السلام عليكم‎‎.

Would you, please, help me?

My site is: http://salyat.com/converter/

here's a code: https://gist.github.com/iamjenechka/73dcc438482d5ab6996cf136cc6f4829

and I got:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.aladhan.com/gToH?date=04-02-2024

**Comment by meezaan** [comment]
That's not the error I get. Here's a screenshot of what I'm seeing:

![image](https://github.com/islamic-network/api.aladhan.com/assets/1839282/a1d783f8-7f65-4ca0-a88c-e8dbee8416e0)

So you're basically calling an incorrect URL.

**Comment by meezaan** [comment]
And the code shows `http`, so how can the error be `https`?

**Comment by iamjenechka** [comment]
Because code that I sent you before differs from the code on the site now. 

When I was waiting for your answer yesterday I tried cors proxy. 

If I'll revert the code to the gist which I sent you yesterday the issue will be about cross-origin request blocked.

**Comment by iamjenechka** [comment]
@meezaan! The changes has been reversed to https://github.com/islamic-network/api.aladhan.com/issues/70#issue-2136856832


please try again from a browser's private window


it's seems it's about CORS request blocking..

**Comment by meezaan** [comment]
> @meezaan! The changes has been reversed to https://github.com/islamic-network/api.aladhan.com/issues/70#issue-2136856832
> 
> 
> 
> 
> 
> please try again from a browser's private window
> 
> 
> 
> 
> 
> it's seems it's about CORS request blocking..on the remote side.
> 
> 
> 
> 
> 
> 
> 
> ![Screenshot_2024-02-16_11-48-13](https://github.com/islamic-network/api.aladhan.com/assets/6221107/a8edff93-4b2f-4010-9a57-cfe4e8386da3)
> 
> 
> 
> 

Sorry I have not had a chance to have a look, but from the screenshot alone if you are calling an http url from an https domain the browser will block your call.

There is no CORS header issue on the api - all the headers are in the code base in the git repo.

**Comment by iamjenechka** [comment]
I already tried https requests as well. Will send you a screenshot as Monday.

**Comment by meezaan** [comment]
> I already tried https requests as well. Will send you a screenshot as Monday.

Sorry I am just geeting to this. I still see the call being made is http and I'm quite sure that is the problem.
