### ISSUE TITLE
Huge difference between city = doha & city = douha

### ISSUE THREAD

**Issue by 2O23** [islamic-network/api.aladhan.com#71]
Hello, for a given date **`01 / 01 / 2024`** could you please check why 

`https://api.aladhan.com/v1/calendarByCity/2024?city=douha&country=qatar&method=18
`

returns -> `"Fajr": "07:03 (+01)",`

AND 

`https://api.aladhan.com/v1/calendarByCity/2024?city=doha&country=qatar&method=18
`

returns -> `"Fajr": "04:58 (+03)",`

the difference between **_doha_** & **_douha_** which are they both the same place is around 2 hours doesn't make any sense!

Thanks :rose:

**Comment by meezaan** [comment]
They are not the same place for the geocoding server, which is almost certainly the reason for the difference. This API uses the 7x geocoding API (https://7x.ax/catalogue/geocode-api). You can test there to see what `Douha` actually returns.

**Comment by 2O23** [comment]
@meezaan Thanks for your fast response sir, but as you can see i'm setting the country to Qatar and only the city is changing so that's why it doesn't make any sense to have a time gap of 2 hours

Thansk :rose:

**Comment by meezaan** [comment]
> @meezaan Thanks for your fast response sir, but as you can see i'm setting the country to Qatar and only the city is changing so that's why it doesn't make any sense to have a time gap of 2 hours
> 
> Thanks 🌹

I don't think it cares what you are setting, unfortunately 😄. Your country and city are concatenated and sent to the geocoding api/server to geocode, and English being the language almost all software evaluation works in, Douha comes before Qatar and probably gets matched somewhere else.
