### ISSUE TITLE
Adding "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan" calculation method

### ISSUE THREAD

**Issue by Yazanmy** [islamic-network/api.aladhan.com#73]
Add the Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan calculation method for Fajr and Isha to the API.

- Angle fo FAJR => 18
- Angle for ISHA => 18
- MAGHRIB => 5 mins

**Location Amman** :
- latitude =>31.9461
- longitude =>35.9238

Here is the official Ministry of Awqaf prayer times for reference.

https://www.awqaf.gov.jo/ar/Pages/PrayerTime

**Comment by Yazanmy** [comment]
https://github.com/islamic-network/prayer-times/pull/5

**Comment by meezaan** [comment]
Thank you for your contribution @Yazanmy. I'll have a look https://github.com/islamic-network/prayer-times/pull/5 and see if I can update the API today, inshaAllah.

**Comment by meezaan** [comment]
See https://api.aladhan.com/v1/timingsByAddress/25-12-2023?address=Amman,%20Jordan.

**Comment by Yazanmy** [comment]
@meezaan Great, Thank you!
