### ISSUE TITLE
tune Parameter Ignored for Method 13 Despite Being Specified

### ISSUE THREAD

**Issue by mustfaunlu** [islamic-network/api.aladhan.com#80]
When using the tune parameter with method=13 in the Aladhan API, custom tuning values are ignored and replaced with hard-coded defaults intended to match Diyanet [calculations.](https://github.com/islamic-network/api.aladhan.com/blob/master/api/Utils/PrayerTimesHelper.php#L343) This behavior prevents users from fine-tuning prayer times as needed.

For example, in the following request:
https://api.aladhan.com/v1/timingsByCity/23-11-2024?city=Karaman&country=Turkey&method=13&tune=0,10,0,0,-40,0,0,0,0&school=1
The tune parameter adjusts the Fajr time correctly but does not affect the Asr time due to this hard-coding.

It would be more flexible and user-friendly if the API prioritized user-provided tune values over the hard-coded defaults. If no tune values are specified, only then should the API fall back to the default values.

Thank you for looking into this!

**Comment by meezaan** [comment]
Salaam @mustfaunlu. Please see https://github.com/islamic-network/api.aladhan.com/pull/81 and let me know if you think this works, or if you want add your adjustment on top of the adjusted timings instead.

**Comment by mustfaunlu** [comment]
@meezaan It looks great to me, and I think it works well as it is.  Thank you :)

**Comment by meezaan** [comment]
> @meezaan It looks great to me, and I think it works well as it is. Thank you :)

Merged. Should be available in a couple of minutes, inshaAllah.
